### PR TITLE
Housekeeping

### LINKED ISSUE #88: place-items and place-content
We should support [place-items](https://developer.mozilla.org/en-US/docs/Web/CSS/place-items) and [place-content](https://developer.mozilla.org/en-US/docs/Web/CSS/place-content)

### LINKED ISSUE #89: Handling of line-height with a multiplier value
Currently with a multiplier value for `line-height`:

```js
transformCss([['line-height', '1.5']])
```
The result is this:

```js
{ lineHeight: 1.5 }
```

React Native treats it as a pixel value instead of a multiplier. We can only calculate the multiplier if we know the font-size of the `Text` element. 

Maybe we should only allow pixels (or other units) to be used with `line-height` and throw an error for a multiplier?

ping @jacobp100

### LINKED ISSUE #114: Parsing errors from tailwind default config
I had a parsing error on the following css:

```
flex: 1 1 0%;
```

I'm pretty sure this is legal css, the unit (% in this case) is optional?

Error printed out as:

`Error: Failed to parse declaration "flex: 1 1 0%"`

Here is the line in tailwind default config, I can work around this, but maybe it makes sense to support optional units on 0  ¯\_(ツ)_/¯ :

https://github.com/tailwindcss/tailwindcss/blob/beff1383533973baeb33436d7c31651b9ea751a8/stubs/defaultConfig.stub.js#L209

### PR DESCRIPTION
**Pull request by jacobp100**
* Updates dependencies
* Optimise build output
* Adds support for percentages in flex shorthand (fixes #114)
* Warns when omitting required units (fixes #89, closes #90)
* Adds support for place content (fixes #88)

I've marked this as breaking as one of the dependency upgrades was breaking (dropped support for node 8), and because there's new warnings

### CODE REVIEW

File: src/devPropertiesWithoutUnitsRegExp.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+let propertiesWitouthUnits
```
Comment (kristerkari) [inline src/devPropertiesWithoutUnitsRegExp.js]: Typo :)

Comment (jacobp100) [reply src/devPropertiesWithoutUnitsRegExp.js]: Haha. It was originally `propertiesWithUnits`, I was just off by one when I renamed it

File: src/index.js [hunk 2]
```diff
@@ -2,57 +2,67 @@
 import parse from 'postcss-value-parser'
 import camelizeStyleName from 'camelize'
 import transforms from './transforms/index'
+import devPropertiesWithoutUnitsRegExp from './devPropertiesWithoutUnitsRegExp'
 import TokenStream from './TokenStream'
 
 // Note if this is wrong, you'll need to change tokenTypes.js too
-const numberOrLengthRe = /^([+-]?(?:\d*\.)?\d+(?:[Ee][+-]?\d+)?)(?:px)?$/i
+const numberOrLengthRe = /^([+-]?(?:\d*\.)?\d+(?:[Ee][+-]?\d+)?)(?:px)?$/
```
Comment (kristerkari) [inline src/index.js]: Hmm.. shouldn't this havew the `/i` to match the unit if it is written in uppercase?

Comment (kristerkari) [reply src/index.js]: ...or can you even write the values uppercase in React Native?

Comment (jacobp100) [reply src/index.js]: Good catch! I only saw the `[Ee]`. Updated this now

Comment (jacobp100) [reply src/index.js]: > ...or can you even write the values uppercase in React Native?
 
The only units RN ever takes is `%`, and `deg` or `rad` in transforms. Just updated these to handle this

File: src/__tests__/placeContent.js [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+it('transforms place content with one value', () => {
+  expect(transformCss([['place-content', 'center']])).toEqual({
+    alignContent: 'center',
+    justifyContent: 'stretch',
+  })
+})
+
+it('does not allow justify content without align content', () => {
+  expect(() => transformCss([['place-content', 'space-everly']])).toThrow()
```
Comment (kristerkari) [inline src/__tests__/placeContent.js]: Should this be `space-evenly`?

Comment (jacobp100) [reply src/__tests__/placeContent.js]: 😅
